name: Run subpackage tests in windows
description: Run tests in windows for a specific package
inputs:
  package_name:
    description: 'Specifies the package build name to run the tests'
    required: true
  cmake_build_type:
    description: 'Specifies the build type on single-configuration generators'
    required: true
    default: 'Release'
runs:
  using: composite
  steps:
  - run: >
      python3 -m pytest ${{ inputs.cmake_build_type }}
    shell: pwsh
