name: Run subpackage tests in windows
description: Run tests in windows for a specific package
inputs:
  package_name:
    description: 'Specifies the package build name to run the tests'
    required: true
runs:
  using: composite
  steps:
  - run: >
      python -m pip install pytest;
      python -m pytest ${{ inputs.package_name }}
    shell: pwsh
      # TODO check if pytest install neeeded
