#!/bin/bash

# DESCRIPTION:
# This script allows to automatically update project elements autogenerated.
# This includes:
# - to re-autogenerate those files that have been autogenerated
# - to re-generate those files that depend on hard links from other documents

# DEPENDENCIES:
# This script depends on dev-utils to be located in ../dev-utils

# WORKSPACE:
# It must be executed from AML-IP main github folder.

# WORK:
# Autogenerated enum files
python3 ../dev-utils/dev_utils/src/automatic_code_generator/cpp/enumeration_builder/enumeration_builder.py \
 --namespaces "eprosima;amlip;types" \
 --enum NodeKind \
 --values "undetermined , discovery , agent , main , computing , status , meta" \
 --output ./amlip_cpp/include/amlip_cpp/types/status/NodeKind.hpp

python3 ../dev-utils/dev_utils/src/automatic_code_generator/cpp/enumeration_builder/enumeration_builder.py \
 --namespaces "eprosima;amlip;types" \
 --enum StateKind \
 --values "unknown , running , stopped , dropped" \
 --output ./amlip_cpp/include/amlip_cpp/types/status/StateKind.hpp
