name: Install eProsima dependencies
description: Install and setup foonatham-memory, Fast CDR and Fast DDS for linking and building applications in Windows
inputs:
  cmake_build_type:
    description: 'Specifies the build type on single-configuration generators'
    required: true
    default: 'Release'
runs:
  using: composite
  steps:
    - name: Install foonatham memory
      shell: pwsh
      run: >
        git clone --recurse-submodules --branch v0.6-2 https://github.com/foonathan/memory.git;
        cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\eprosima\install `
          -DBUILD_SHARED_LIBS=OFF -DFOONATHAN_MEMORY_BUILD_TOOLS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON `
          -DFOONATHAN_MEMORY_BUILD_TESTS=OFF -Ax64 -T host=x64 -B build\memory memory;
        cmake --build build\memory --config ${{ inputs.cmake_build_type }} --target install

    - name: Install Fast CDR
      shell: pwsh
      run: >
        git clone https://github.com/eProsima/Fast-CDR.git;
        cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\eprosima\install `
          -DCMAKE_PREFIX_PATH=${{ github.workspace }}\eprosima\install `
          -Ax64 -T host=x64 -B build\fastcdr Fast-CDR;
        cmake --build build\fastcdr --config ${{ inputs.cmake_build_type }} --target install

    - name: Install Fast DDS
      shell: pwsh
      run: >
        git clone https://github.com/eProsima/Fast-DDS.git;
        cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\eprosima\install `
          -DCMAKE_PREFIX_PATH=${{ github.workspace }}\eprosima\install `
          -DTHIRDPARTY=ON -DSECURITY=ON -DCOMPILE_EXAMPLES=OFF -DEPROSIMA_BUILD_TESTS=OFF `
          -DINTERNAL_DEBUG=ON -DSHM_TRANSPORT_DEFAULT=OFF -Ax64 -T host=x64 -B build\fastdds Fast-DDS;
        cmake --build build\fastdds --config ${{ inputs.cmake_build_type }} --target install

    - name: Install Dev Utils
      shell: pwsh
      run: >
        git clone https://github.com/eProsima/dev-utils.git;
        "cmake_utils cpp_utils".Split(" ") | ForEach {
          echo "building package: $_";
          cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\eprosima\install `
            -DCMAKE_PREFIX_PATH=${{ github.workspace }}\eprosima\install `
            -Ax64 -T host=x64 -B build\$_ dev-utils/$_;
          cmake --build build\$_ --config ${{ inputs.cmake_build_type }} --target install;
        }

    - name: Install DDS Router
      shell: pwsh
      run: >
        git clone https://github.com/eProsima/DDS-Router.git;
        "ddsrouter_core;ddsrouter_core ddsrouter_yaml;ddsrouter_yaml ddsrouter_tool;tools/ddsrouter_tool".Split(" ") | ForEach {
          $subpackage_arr =$_.Split(";")
          $subpackage= $subpackage_arr[0]
          $subpackage_dir= $subpackage_arr[1]
          echo "building package: $subpackage";
          cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\eprosima\install `
            -DCMAKE_PREFIX_PATH='C:\Program Files\yamlcpp;${{ github.workspace }}\eprosima\install' `
            -Ax64 -T host=x64 -B build\$subpackage DDS-Router/$subpackage_dir;
          cmake --build build\$subpackage --config ${{ inputs.cmake_build_type }} --target install;
        }
