
#include "amlip.idl"

enum NodeKind
{
    UNDETERMINED,
    DISCOVERY,
    AGENT,
    MAIN,
    COMPUTATIONAL,
    EDGE,
    STATUS
};

enum StatusKind
{
    RUNNING,
    DISABLED
};

struct Status
{
    AmlipId id;
    NodeKind node_kind;
    StatusKind status;
};
