name: build_eprosima_dependencies

on:
  workflow_dispatch:
    inputs:
      foonathan_memory_vendor_branch:
        description: 'Branch or tag of eProsima/foonathan_memory_vendor repository (https://github.com/eProsima/foonathan_memory_vendor)'
        required: true
        default: 'master'
      fastcdr_branch:
        description: 'Branch or tag of eProsima/Fast-CDR repository (https://github.com/eProsima/Fast-CDR)'
        required: true
        default: '1.1.x'
      fastdds_branch:
        description: 'Branch or tag of eProsima/Fast-DDS repository (https://github.com/eProsima/Fast-DDS)'
        required: true
        default: '2.11.x'
      utils_branch:
        description: 'Branch or tag of eProsima/dev-utils repository (https://github.com/eProsima/dev-utils)'
        required: true
        default: 'main'
      ddspipe_branch:
        description: 'Branch or tag of eProsima/DDS-Pipe repository (https://github.com/eProsima/DDS-Pipe)'
        required: true
        default: 'main'
      ddsrouter_branch:
        description: 'Branch or tag of eProsima/DDS-Router repository (https://github.com/eProsima/DDS-Router)'
        required: true
        default: 'main'
  schedule:
    - cron: '0 0 * * *'

jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cmake-config:
          - 'Release'
          - 'Debug'
    env:
      CXXFLAGS: /MP
      OPENSSL64_ROOT: "C:/Program Files/OpenSSL-Win64"

    steps:
      - name: Sync eProsima/AML-IP repository
        uses: actions/checkout@v2
        with:
          path: AML-IP

      - name: Install OpenSSL
        uses: ./AML-IP/.github/actions/install-openssl-windows

      - name: Install yaml-cpp
        uses: ./AML-IP/.github/actions/install-yamlcpp-windows
        with:
          cmake_build_type: ${{ matrix.cmake-config }}

      - name: Install eProsima dependencies
        uses: ./AML-IP/.github/actions/install-eprosima-dependencies-windows
        env:
          DEFAULT_FOONATHAN_BRANCH: 'master'
          DEFAULT_FASTCDR_BRANCH: '1.1.x'
          DEFAULT_FASTDDS_BRANCH: '2.11.x'
          DEFAULT_UTILS_BRANCH: 'main'
          DEFAULT_DDDSPIPE_BRANCH: 'main'
          DEFAULT_DDSROUTER_BRANCH: 'main'
        with:
          cmake_build_type: ${{ matrix.cmake-config }}
          foonathan_memory_vendor_branch: ${{ github.event.inputs.foonathan_memory_vendor_branch || env.DEFAULT_FOONATHAN_BRANCH }}
          fastcdr_branch: ${{ github.event.inputs.fastcdr_branch || env.DEFAULT_FASTCDR_BRANCH }}
          fastdds_branch: ${{ github.event.inputs.fastdds_branch || env.DEFAULT_FASTDDS_BRANCH }}
          utils_branch: ${{ github.event.inputs.utils_branch || env.DEFAULT_UTILS_BRANCH }}
          ddspipe_branch: ${{ github.event.inputs.ddspipe_branch || env.DEFAULT_DDDSPIPE_BRANCH }}
          ddsrouter_branch: ${{ github.event.inputs.ddsrouter_branch || env.DEFAULT_DDSROUTER_BRANCH }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: windows_${{ matrix.cmake-config }}_eprosima_dependencies_install
          path: ${{ github.workspace }}\eprosima\install

  ubuntu-build:
    runs-on: ubuntu-latest
    environment:
      name: codecov

    steps:
      - name: Sync eProsima/AML-IP repository
        uses: actions/checkout@v2
        with:
          path: src/AML-IP

      - name: Avoid AML-IP build
        run: |
          touch ./src/AML-IP/COLCON_IGNORE

      - name: Install apt packages
        uses: ./src/AML-IP/.github/actions/install-apt-packages

      - name: Install colcon
        uses: eProsima/eProsima-CI/ubuntu/install_colcon@v0

      - name: Install Python packages
        uses: eProsima/eProsima-CI/ubuntu/install_python_packages@v0
        with:
          packages: \
            black==22.3.0 \
            doc8==0.8.0 \
            GitPython \
            setuptools \
            gcovr==5.0 \
            sphinx_rtd_theme==0.4.3 \
            sphinx==3.0.3 \
            sphinx-tabs==3.2.0 \
            sphinxcontrib-imagehelper==1.1.1 \
            sphinxcontrib.spelling==5.0.0 \
            vcstool \
            flake8==5.0.4 \
            flake8-quotes \
            pytest \
            pytest-timeout

      - name: Fetch dependencies repositories
        run: |
          vcs import src <  src/AML-IP/.github/workflows/ci.repos
          cd src/foonathan_memory_vendor && git checkout ${{ inputs.foonathan_memory_vendor_branch }} && cd ../..
          cd src/fastcdr && git checkout ${{ inputs.fastcdr_branch }} && cd ../..
          cd src/fastdds && git checkout ${{ inputs.fastdds_branch }} && cd ../..
          cd src/dev-utils && git checkout ${{ inputs.utils_branch }} && cd ../..
          cd src/ddspipe && git checkout ${{ inputs.ddspipe_branch }} && cd ../..
          cd src/ddsrouter && git checkout ${{ inputs.ddsrouter_branch }} && cd ../..

      - name: Build workspace
        run: |
          colcon build --event-handlers=console_direct+

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_eprosima_dependencies_install
          path: install
