# Nightly test workflow for AML-IP
name: test

on:
  schedule:
    - cron: '0 5 * * *'

jobs:

  reusable_tests_v2:
    name: reusable_tests_v2
    uses: eProsima/AML-IP/.github/workflows/reusable-workflow.yml
    with:
      custom_version_build: 'v2'
      dependencies_artifact_postfix: '_nightly'

  # Uncomment this block to run the tests for Fast DDS v3 when AML-IP is updated
  # reusable_tests_v3:
  #   name: reusable_tests_v3
  #   uses: eProsima/AML-IP/.github/workflows/reusable-workflow.yml
  #   with:
  #     custom_version_build: 'v3'
  #     dependencies_artifact_postfix: '_nightly'
